#!/usr/bin/env node
// Builds the showcase into .stage/ (git-ignored) for one or both hosts.
//
//   node scripts/stage.mjs --host electron|tauri|all [--lab] [--identity FILE]
//
// .stage/package.json     the staged manifest: package.json with the local
//                         identity merged in (identity.local.json,
//                         git-ignored), so the uid is the same on both hosts
// .stage/electron/        the ow-electron app folder: `ow-electron .stage/electron`
// .stage/tauri/           the ow-tauri page (tauri.conf.json frontendDist)
// .stage/tauri.conf.json  the Tauri config override with the staged identity
//                         (product name, version, plugins.overwolf author,
//                         name and uid): `tauri dev|build --config`
// .stage/tauri-lab/       with --lab: the ow-tauri page with the lab driver
//                         (e2e/tauri-driver.js) in front of it
//
// The identity file holds `author`, `productName` and an optional `uid`
// (a console-assigned uid, written as `overwolf.uid`); `name` and `version`
// are taken too. Its values are never printed.

import { spawnSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

import { rolldown } from 'rolldown';

import { bundles } from '../rolldown.config.mjs';
import { stagedManifest, tauriConfig } from './manifest.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(root, '..', '..');
const stage = join(root, '.stage');

const { values: opts } = parseArgs({
  options: {
    host: { type: 'string', default: 'all' },
    lab: { type: 'boolean', default: false },
    identity: { type: 'string' },
  },
});
if (!['electron', 'tauri', 'all'].includes(opts.host)) {
  console.error(`stage: unknown --host ${opts.host} (electron, tauri or all)`);
  process.exit(2);
}
const hosts = opts.host === 'all' ? ['electron', 'tauri'] : [opts.host];

function readIdentity() {
  const file = opts.identity ? resolve(opts.identity) : join(root, 'identity.local.json');
  if (!existsSync(file)) {
    if (opts.identity) throw new Error(`identity file not found: ${file}`);
    console.log('stage: no identity.local.json; using the placeholder identity of package.json');
    return null;
  }
  console.log(`stage: local identity from ${opts.identity ? file : 'identity.local.json'}`);
  return JSON.parse(readFileSync(file, 'utf8'));
}

function ensureApiBuilt() {
  const built = join(repo, 'packages', 'api', 'dist', 'adview', 'index.js');
  if (existsSync(built)) return;
  console.log('stage: building tauri-plugin-overwolf-api (packages/api/dist is missing)');
  const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  const r = spawnSync(npm, ['run', 'build', '--workspace', 'tauri-plugin-overwolf-api'], {
    cwd: repo,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  if (r.status !== 0) throw new Error('tauri-plugin-overwolf-api build failed');
}

async function bundle(host, outDir, entry) {
  for (const options of bundles(host, { outDir, entry })) {
    const { output, ...input } = options;
    const build = await rolldown(input);
    try {
      await build.write(output);
    } finally {
      await build.close();
    }
  }
  for (const file of ['index.html', 'styles.css']) {
    copyFileSync(join(root, 'src', 'renderer', file), join(outDir, 'renderer', file));
  }
}

function writeJson(file, value) {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);
}

async function main() {
  const base = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const manifest = stagedManifest(base, readIdentity());
  mkdirSync(stage, { recursive: true });
  writeJson(join(stage, 'package.json'), manifest);

  for (const host of hosts) {
    if (host === 'electron') {
      const out = join(stage, 'electron');
      rmSync(out, { recursive: true, force: true });
      await bundle('electron', out);
      // ow-electron reads the app's package.json from its folder.
      writeJson(join(out, 'package.json'), manifest);
      console.log(`stage: ow-electron app -> ${out}`);
      continue;
    }
    ensureApiBuilt();
    const variants = [{ dir: 'tauri' }];
    if (opts.lab) {
      const entry = join(stage, 'lab', 'entry.ts');
      mkdirSync(dirname(entry), { recursive: true });
      writeFileSync(
        entry,
        [
          '// Generated by scripts/stage.mjs --lab: the lab driver starts before the page.',
          `import ${JSON.stringify(join(root, 'e2e', 'tauri-driver.js'))};`,
          `import ${JSON.stringify(join(root, 'src', 'tauri', 'index.ts'))};`,
          '',
        ].join('\n'),
      );
      variants.push({ dir: 'tauri-lab', entry });
    }
    for (const { dir, entry } of variants) {
      const out = join(stage, dir);
      rmSync(out, { recursive: true, force: true });
      await bundle('tauri', out, entry);
      console.log(`stage: ow-tauri page -> ${out}`);
    }
    writeJson(join(stage, 'tauri.conf.json'), tauriConfig(manifest));
  }
}

main().catch((error) => {
  console.error(`stage: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
