#!/usr/bin/env node
// Builds the showcase into .stage/ (git-ignored) for one or both hosts.
//
//   node scripts/stage.mjs --host electron|tauri|all [--lab] [--identity FILE]
//
// .stage/package.json   the staged manifest: package.json with the local
//                       identity merged in (identity.local.json, git-ignored),
//                       so the uid is the same on both hosts. The Tauri build
//                       embeds it (src-tauri/build.rs).
// .stage/electron/      the ow-electron app folder: `ow-electron .stage/electron`
// .stage/tauri/         the ow-tauri frontend (tauri.conf.json frontendDist)
// .stage/tauri.conf.json  `tauri dev --config` override: productName and
//                       version from the staged manifest
// .stage/tauri-lab/     with --lab: the ow-tauri frontend with the lab driver
//                       (e2e/tauri-driver.js) in front of the main process
//
// The identity file holds `author`, `productName` and an optional `uid`
// (a console-assigned uid, written as `overwolf.uid`); `name` and `version`
// are taken too. Its values are never printed.

import { spawnSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

import { rolldown } from 'rolldown';

import { bundles } from '../rolldown.config.mjs';
import { stagedManifest } from './manifest.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(root, '..', '..');
const stage = join(root, '.stage');

const { values: opts } = parseArgs({
  options: {
    host: { type: 'string', default: 'all' },
    lab: { type: 'boolean', default: false },
    identity: { type: 'string' },
  },
});
if (!['electron', 'tauri', 'all'].includes(opts.host)) {
  console.error(`stage: unknown --host ${opts.host} (electron, tauri or all)`);
  process.exit(2);
}
const hosts = opts.host === 'all' ? ['electron', 'tauri'] : [opts.host];

function readIdentity() {
  const file = opts.identity ? resolve(opts.identity) : join(root, 'identity.local.json');
  if (!existsSync(file)) {
    if (opts.identity) throw new Error(`identity file not found: ${file}`);
    console.log('stage: no identity.local.json; using the placeholder identity of package.json');
    return null;
  }
  console.log(`stage: local identity from ${opts.identity ? file : 'identity.local.json'}`);
  return JSON.parse(readFileSync(file, 'utf8'));
}

function ensureOwTauriBuilt() {
  const built = join(repo, 'packages', 'ow-tauri', 'dist', 'electron', 'index.js');
  if (existsSync(built)) return;
  console.log('stage: building ow-tauri (packages/ow-tauri/dist is missing)');
  const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  const r = spawnSync(npm, ['run', 'build', '--workspace', 'ow-tauri'], {
    cwd: repo,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  if (r.status !== 0) throw new Error('ow-tauri build failed');
}

async function bundle(host, outDir, mainEntry) {
  for (const options of bundles(host, { outDir, mainEntry })) {
    const { output, ...input } = options;
    const build = await rolldown(input);
    try {
      await build.write(output);
    } finally {
      await build.close();
    }
  }
  for (const file of ['index.html', 'styles.css']) {
    copyFileSync(join(root, 'src', 'renderer', file), join(outDir, 'renderer', file));
  }
}

function writeJson(file, value) {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);
}

async function main() {
  const base = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const manifest = stagedManifest(base, readIdentity());
  mkdirSync(stage, { recursive: true });
  writeJson(join(stage, 'package.json'), manifest);

  for (const host of hosts) {
    if (host === 'electron') {
      const out = join(stage, 'electron');
      rmSync(out, { recursive: true, force: true });
      await bundle('electron', out);
      // ow-electron reads the app's package.json from its folder.
      writeJson(join(out, 'package.json'), manifest);
      console.log(`stage: ow-electron app -> ${out}`);
      continue;
    }
    ensureOwTauriBuilt();
    const variants = [{ dir: 'tauri' }];
    if (opts.lab) {
      const entry = join(stage, 'lab', 'main-entry.ts');
      mkdirSync(dirname(entry), { recursive: true });
      writeFileSync(
        entry,
        [
          '// Generated by scripts/stage.mjs --lab: the lab driver runs before the app.',
          `import ${JSON.stringify(join(root, 'e2e', 'tauri-driver.js'))};`,
          `import ${JSON.stringify(join(root, 'src', 'main', 'main.ts'))};`,
          '',
        ].join('\n'),
      );
      variants.push({ dir: 'tauri-lab', mainEntry: entry });
    }
    for (const { dir, mainEntry } of variants) {
      const out = join(stage, dir);
      rmSync(out, { recursive: true, force: true });
      await bundle('tauri', out, mainEntry);
      // The page the plugin loads into the hidden main webview.
      writeFileSync(
        join(out, 'main', 'main.html'),
        '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <title>main</title>\n  </head>\n  <body>\n    <script src="main.js"></script>\n  </body>\n</html>\n',
      );
      console.log(`stage: ow-tauri frontend -> ${out}`);
    }
    writeJson(join(stage, 'tauri.conf.json'), {
      productName: manifest.productName ?? manifest.name,
      version: manifest.version,
    });
  }
}

main().catch((error) => {
  console.error(`stage: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
